version: "2"
services:
  awslogs-exporter:
    build:
      context: ../..
      dockerfile: environment/dev/Dockerfile
    volumes:
      - ../..:/go/src/github.com/houserater/awslogs-exporter
    environment:
      - ENVIRONMENT=local
      - AWS_REGION
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

    command: "bin/awslogs-exporter --aws.region=us-east-1"
    ports:
      - "9223:9223"
